//images and icons
export const clearDay = 'https://res.cloudinary.com/dhwvpqguu/image/upload/v1714134045/weather-app/sunny_sfiuog.jpg'
export const clearNight = 'https://res.cloudinary.com/dhwvpqguu/image/upload/v1714212829/weather-app/night-clearr_siwpv7.png'
export const rainyDay = 'https://res.cloudinary.com/dhwvpqguu/image/upload/v1714134074/weather-app/rainy_pa6xy8.jpg'
export const rainyNight = 'https://res.cloudinary.com/dhwvpqguu/image/upload/v1714134161/weather-app/night-rainy_trky4c.jpg'
export const cloudyDay = 'https://res.cloudinary.com/dhwvpqguu/image/upload/v1714283041/weather-app/cloud-day_y8w2io.jpg'
export const cloudyNight = 'https://res.cloudinary.com/dhwvpqguu/image/upload/v1714283055/weather-app/cloud-night_oeobmx.jpg'
export const clearDaySvg = './assets/icons/day.svg'
export const clearNightSvg = './assets/icons/night.svg'
export const rainySvg = './assets/icons/rainy-7.svg'
export const cloudyNightSvg = './assets/icons/partiallt-cloudy-night.svg'
export const cloudyDaySvg = './assets/icons/partiallt-cloudy-day.svg'
export const thunderstromSvg = './assets/icons/thunder.svg'
export const snowSvg = './assets/icons/snow.svg'
